# SPDX-FileCopyrightText: 2026 CAI contributors
# SPDX-License-Identifier: MIT
from __future__ import annotations


CAI_OWNED_TRANSPORT_PROTOCOL = "cai-owned-llm-shard-transport"
CAI_OWNED_TRANSPORT_PROTOCOL_VERSION = 1
CAI_OWNED_TRANSPORT_RUNTIME_VERSION = "cai-owned-runtime/0.1"
CAI_OWNED_TRANSPORT_SESSION_OFFER_SCHEMA_VERSION = 1
CAI_OWNED_TRANSPORT_PROOF_SCHEMA_VERSION = 1
CAI_OWNED_TRANSPORT_BATCH_ENVELOPE_SCHEMA_VERSION = 1
CAI_OWNED_TRANSPORT_FRAME_SCHEMA_VERSION = 1
CAI_OWNED_TRANSPORT_HASH_CHAIN_SCHEMA_VERSION = 1
CAI_OWNED_TRANSPORT_EXECUTION_DAG_SCHEMA_VERSION = 1
CAI_OWNED_LLM_HANDOFF_SCHEMA_VERSION = 1
CAI_OWNED_LLM_HANDOFF_ABI = "cai-llm-shard-handoff-v1"

EXECUTION_MODE_SINGLE_NODE = "single_node"
EXECUTION_MODE_LLAMA_CPP_RPC_LOW_LATENCY = "llama_cpp_rpc_low_latency"
EXECUTION_MODE_LLAMA_CPP_RPC_PROVEN_UNKNOWN_LATENCY = (
    "llama_cpp_rpc_proven_unknown_latency"
)
EXECUTION_MODE_CAI_OWNED_TRANSPORT_REQUIRED = "cai_owned_transport_required"

CAI_OWNED_TRANSPORT_REQUIRED_CAPABILITIES = (
    "session_envelope",
    "model_shard_lock",
    "activation_batch_stream",
    "decode_batch_stream",
    "per_shard_execution_receipts",
    "route_health_feedback",
)

CAI_OWNED_TRANSPORT_RUNTIME_PHASES = (
    "negotiate_session",
    "lock_model_shards",
    "prefill_activation_batches",
    "decode_activation_batches",
    "finalize_receipts",
)

CAI_OWNED_TRANSPORT_BATCH_PHASES = (
    "prefill_activation_batches",
    "decode_activation_batches",
)
CAI_OWNED_TRANSPORT_EXECUTION_PIPELINE_FULL_PREFILL_DECODE = "full_prefill_decode"
CAI_OWNED_TRANSPORT_EXECUTION_PIPELINE_SINGLE_PASS_FINAL_DECODE = (
    "single_pass_final_decode"
)
CAI_OWNED_TRANSPORT_FRAME_KINDS = (
    "activation",
    "decode",
    "kv_cache",
    "logits",
    "bytes_test",
)
CAI_OWNED_LLM_HANDOFF_TENSOR_ENCODINGS = (
    "raw-le",
    "ggml-tensor-v1",
    "safetensors-fragment-v1",
)
CAI_OWNED_TRANSPORT_PAYLOAD_COMPRESSIONS = ("gzip",)
CAI_OWNED_TRANSPORT_DEFAULT_BATCH_LEASE_SECONDS = 60.0
CAI_OWNED_TRANSPORT_DEFAULT_BATCH_CLAIM_TIMEOUT_SECONDS = 120.0
CAI_OWNED_TRANSPORT_DEFAULT_MAX_BATCH_ATTEMPTS = 3
CAI_OWNED_TRANSPORT_SESSION_OFFER_MAX_AGE_SECONDS = 15 * 60.0
CAI_OWNED_TRANSPORT_BATCH_ENVELOPE_MAX_AGE_SECONDS = 15 * 60.0
CAI_OWNED_TRANSPORT_CLOCK_SKEW_SECONDS = 5 * 60.0
CAI_OWNED_TRANSPORT_PAYLOAD_RETENTION_SECONDS = 7 * 24 * 60 * 60.0
CAI_OWNED_TRANSPORT_REPLAY_CACHE_RETENTION_SECONDS = 24 * 60 * 60.0
CAI_OWNED_TRANSPORT_OVERLAY_URL_PREFIX = "cai-overlay:"
CAI_OWNED_TRANSPORT_AUTH_TOKEN_ENV = "CAI_PEER_TRANSPORT_TOKEN"
CAI_OWNED_TRANSPORT_REQUIRE_AUTH_ENV = "CAI_REQUIRE_PEER_TRANSPORT_AUTH"
CAI_OWNED_TRANSPORT_AUTH_HEADER = "X-CAI-Transport-Token"
CAI_OWNED_TRANSPORT_CHAIN_HEADER = "X-CAI-Chain-Id"
CAI_OWNED_TRANSPORT_LOCAL_RUNTIME_TOKEN_ENV = "CAI_LOCAL_RUNTIME_TOKEN"
CAI_OWNED_TRANSPORT_REQUIRE_LOCAL_RUNTIME_AUTH_ENV = (
    "CAI_REQUIRE_LOCAL_RUNTIME_AUTH"
)
